[[language]]
name = "python"
formatter = { command = "ruff", args = ["format", "-"] }
auto-format = true

[[language]]
name = "rust"
formatter = { command = "rustfmt" }
auto-format = true

[language-server.rust-analyzer.config]
check.command = "clippy"
inlayHints.lifetimeElisionHints.enable = "skip_trivial"
inlayHints.bindingModeHints.enable = true
